cat <<EOF > 1-rolling-update.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: test
  labels:
    run: myapp-svc
    color: blue
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
  - port: 8181
    protocol: TCP
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: test
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # Max number of Pods that can be unavailable during the update process
      maxSurge: 1 # Max number of Pods that can be created over the desired number of Pods
      # maxUnavailable: 25%
      # maxSurge: 25%
  replicas: 10
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: aputra/myapp-171:v1
          ports:
            - name: http
              containerPort: 8181
          startupProbe:
            tcpSocket:
              port: 8181
            initialDelaySeconds: 20
            periodSeconds: 5
EOF
