apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: alpine
    name: test
    command: ['/bin/sh', '-c', 'while true; do echo "hello $(date)" > /ddn/index.html; sleep 1; done']
    volumeMounts:
    - mountPath: /ddn
      name: cache-volume
  - image: nginx
    name: nginx
    volumeMounts:
    - name: cache-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: cache-volume
    emptyDir:
      medium: "Memory"
      sizeLimit: 50Mi

