apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxpod
  name: nginxpod
spec:
  containers:
  - image: nginx
    name: nginxpod
    resources: {}
  # nodeSelector:
  #   oddWorker: 'false'
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: oddWorker
            operator: NotIn
            # operator: In
            values:
            - 'true'
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
