apiVersion: v1
kind: Service
metadata:
  name: management-ui
  namespace: management-ui
spec:
  selector:
    role: management-ui
  ports:
    - port: 9001
      targetPort: 9001
  type: LoadBalancer
