apiVersion: v1
kind: PersistentVolume
metadata: 
  name: jenkins-pv
  namespace: jenkins-ns
spec:
  storageClassName: jenkins-pv
  accessModes: 
    - ReadWriteMany
  capacity: 
    storage: 2Gi
  nfs: 
    path: /mnt/nfs_share
    server: ubuntu.example.com
