apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: echo-server
spec:
  selector:
    name: my-ds
  # type: ClusterIP
  # type: LoadBalancer
  ports:
  - port: 8181
    protocol: TCP
    targetPort: 80
  externalIPs: 
    - 198.19.0.100
