apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
  namespace: alpine
  labels:
    app: alpine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine:3.18.2
        command:
          - /bin/sh
          - "-c"
          - "tail -f /dev/null"
