apiVersion: v1
kind: Namespace
metadata:
  name: echo-server
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: echo-server
  namespace: echo-server
  labels:
    app: echo-server
    k8s-app: echo-server
spec:
  selector:
    matchLabels:
      name: echo-server
  template:
    metadata:
      labels:
        name: echo-server
    spec:
      containers:
      - name: echo-server
        image: php82_nginx125:3.18.2
        env:
        - name: TCP_PORT
          value: "1234"
        - name: UDP_PORT
          value: "5678"
        - name: TZ
          value: "EAST+5EDT,M3.2.0/2,M11.1.0/2"
        - name: TIMEZONE
          value: "America/New_York"
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
